name = Front page layout
description = Layout for frontpage
template = front-layout

; ========================================
; Regions
; ========================================
regions[branding] = Branding
regions[navigation] = Navigation
regions[slider] = Slider
regions[service_slider] = Service Slider
regions[who] = Who we are
regions[services] = Services
regions[content] = Content
regions[map] = Map
regions[footer] = Footer

; ========================================
; Styles
; ========================================
stylesheets[all][] = css/layouts/front/omega_codepulse-front.layout.css